### PR TITLE
[BUG] Get the Success Message on the Interaction Login Button Channel

### LINKED ISSUE #113: [BUG] Succesful Login Message on Last Generated `Login Button` Room Even Though Interaction from Other Room
### Description:
- When we are generating Login Button with `/github login` in two different channel [channel1 and channel2 one by one] and interacting from the loginbutton of channel1 we are getting successful message in channel2.

### Steps to reproduce:

1.   Run  /github login command in two different Channel
2.   login from  button in first channel in which you run the above command
3. check the message is being received in different channel.

### Expected behavior:
- Message Should be received on Same Channel where the interaction Happens

### Actual behavior:
- Message is received in channel where `/github login` command is run last.

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Issue(s) 
- Closes #113 

### Before
Interaction

### After
interactionSolved

### CODE REVIEW

File: github/handlers/ExecuteBlockActionHandler.ts [hunk 1]
```diff
@@ -1044,6 +1044,18 @@ export class ExecuteBlockActionHandler {
...
+                    const {user, room} = context.getInteractionData();
+                    if(room){
+                        await storeInteractionRoomData(
+                            this.persistence,
+                            user.id,
+                            room.id
+                        );
+                    }
+                    break;
+                }
```
Comment (samad-yar-khan) [inline github/handlers/ExecuteBlockActionHandler.ts:1058]: @Nabhag8848 We are persisting this. But is this memory being freed up ?

Comment (Nabhag8848) [reply github/handlers/ExecuteBlockActionHandler.ts:1058]: Yep. Right over here: https://github.com/RocketChat/Apps.Github22/blob/main/github/GithubApp.ts#L85
We were using the same mechanism of storing interaction roomId. 
- But before we stored the roomId during execution of command which lead to this bug.
- Now we are storing on interaction of button.

**Review by samad-yar-khan — APPROVED** [review]
LGTM
