### PR TITLE
[FIX] subscribeall doesn't provide info when not loggedIn

### LINKED ISSUE #64: [BUG] subscribeall command isn't providing loginInfo to non authorised user
### Description:
- When non authorised user running `/github username/repo subscribe` it isn't providing the loginInfo and not letting user know about the same.

### Steps to reproduce:

1. Run `/github username/repo subscribe` when not loggedIn

### Expected behavior:
- should provide the loginInfo

### Actual behavior:
- isn't providing the login info

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Issue(s) 
Closes #64 

## Proposed changes (including videos or screenshots)
- Now that when non-authorised user will run the command `/github username/repo subscribe` will provide the login info notification.

### CODE REVIEW

File: github/handlers/EventHandler.ts [hunk 1]
```diff
@@ -118,6 +118,14 @@ export async function SubscribeAllEvents(
         } catch (error) {
             console.log("SubcommandError", error);
         }
+    } else {
```
Comment (samad-yar-khan) [inline github/handlers/EventHandler.ts:121]: Thanks for fixing this case @Nabhag8848 . We must have missed this during implementation. 💯

**Review by samad-yar-khan — APPROVED** [review]

File: github/handlers/EventHandler.ts [hunk 2]
```diff
@@ -118,6 +118,14 @@ export async function SubscribeAllEvents(
...
+        await sendNotification(
+            read,
+            modify,
+            context.getSender(),
+            room,
+            "Login to subscribe to repository events ! `/github login`"
+        );
```
Comment (samad-yar-khan) [inline github/handlers/EventHandler.ts:128]: Thanks for adding this @Nabhag8848 . LGTM  :100:

**Review by samad-yar-khan — APPROVED** [review]
