### PR TITLE
[FIX] commands and buttons, unexpected results when repository in github doesn't exist

### LINKED ISSUE #40: [BUG] Interactive Buttons Giving Unexpected Results When Provided Repository in Command doesn't exist
### Description:

- By executing `/github Username/RepositoryName` and if the Provided **Username/RepositoryName** doesn't exist. Interacting with Actions Buttons giving unexpected outputs. Specially when interacting with `Overview` Action Button giving undefined in several places more precisely in following: 
     
       1. Username/Repository
       2. Number of Stars
       3. Number of Issues
       4. Number of Forks
       5. Description

- User might make `Typo` when using commands and this would lead to above unexpected result.

### For Example: 

- By executing `/github Rocket.Chat/Rocket.Chat` and then interacting with the Overview Button Specially will lead to problem specified above as there is no Username/Org matching `Rocket.Chat`. 

### Steps to reproduce:

1. Run command `/github Username/RepositoryName` by having Fake **username/repository**  which doesn't exist in Github. 
2. Interact with Action Buttons Specially `Overview`.
3. check the undefined results.

### Expected behavior:
-  What we actually can do, **Check if the repository exist before showing the action buttons**. Only show the Action Buttons if the `repository` exists and now instead of sending `Hey {username}!` via bot everytime before we show the Buttons.Now, if the repository doesn't exist we will avoid showing ActionButtons and Send the message `Hey { username } ! Provided username and/or repository doesn't exist `. and in case of everything goes fine meaning repository exist will show the Buttons as well as the text `Hey {username}!`.

 Screenshot from 2022-12-05 21-01-09

### Actual behavior:
- As discussed in the **Description** section, you can see the the `undefined` results at several places.

Screenshot from 2022-12-04 15-12-39

### Note: 
- [x] Willing to work on the issue.

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Issue(s) 
- Closes #40 

## Proposed changes (including videos or screenshots)

- Now for every command having repoName will be validate the repoName and if its invalid will Send the message `Hey { username } ! Provided username and/or repository doesn't exist`. **Further** In case of Action buttons command, will only show buttons if the repo exist.

## Further comments

- [x] This PR is ready to review.

### CODE REVIEW

**Comment by Nabhag8848** [comment]
Hey @samad-yar-khan, Can you review the Fixes. Thanks.

**Comment by Nabhag8848** [comment]
Hey @samad-yar-khan, Can you review the Fixes. Thanks.

**Comment by samad-yar-khan** [comment]
@Nabhag8848 Thanks a lot for your PR, I will take a look.

**Comment by samad-yar-khan** [comment]
Hey @Nabhag8848 Can you please rebase your branch ? Will make it easier to review

**Comment by Nabhag8848** [comment]
> Hey @Nabhag8848 Can you please rebase your branch ? Will make it easier to review

yep! its done now.

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]

File: github/helpers/githubSDK.ts [hunk 1]
```diff
@@ -726,3 +726,20 @@ export async function updateGithubIssues(
...
+
+export async function isRepositoryExist(
+    http: IHttp,
+    repoName: string
+): Promise<boolean> {
+    const response = await http.get(`${BaseRepoApiHost}${repoName}`, {
+        headers: {
+            "Content-Type": "application/json",
+        },
+    });
```
Comment (samad-yar-khan) [inline github/helpers/githubSDK.ts:738]: @Nabhag8848 Handling the endpoint for unauthorized users should happen conditionally. This will return false for any private repo. We should ideally try get the access token, if it exists we add it to the header else we just skip it.

Comment (samad-yar-khan) [reply github/helpers/githubSDK.ts:738]: [This code snippet should help](https://github.com/RocketChat/Apps.Github22/blob/main/github/helpers/githubSDK.ts#L664-L677).

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]
@Nabhag8848 the method `isRepositoryExist` will return `false` for any private repo. I think we should conditionally handle this if the user is logged in.

File: github/helpers/githubSDK.ts (hunk 1 above)
Comment (Nabhag8848) [reply github/helpers/githubSDK.ts:738]: Yep @samad-yar-khan , will fix this rn.
 i found another issue within this case when running command having private repo **without login**. So our message says `Hey {sender} Provided username and/or repository doesn't exist` even though the repo exist actually but user is not loggedIn. This leads to we will need to change the message to `Hey {sender} Provided repository doesn't exist or you are not logged in`

Comment (samad-yar-khan) [reply github/helpers/githubSDK.ts]: @Nabhag8848 We can show `Hey {sender} Provided repository doesn't exist or you need to login to access private repo.` incase the user is not logged in but if the token is there we can always show `Hey {sender} Provided username and/or repository doesn't exist`

File: github/handlers/HandleInvalidRepoName.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+export async function HandleInvalidRepoName(
+    repoName: string,
+    http: IHttp,
+    app: GithubApp,
+    modify: IModify,
+    sender: IUser,
+    read: IRead,
+    room: IRoom
+): Promise<boolean> {
+    const accessTokenInfo = (await getAccessTokenForUser(
```
Comment (samad-yar-khan) [inline github/handlers/HandleInvalidRepoName.ts:22]: @Nabhag8848 Although the variable name `accessTokenInfo` makes sense, we have uses `accessToken` for this data throughout the code. Keeping the naming patterns consistent will help future contributors as well.

File: github/handlers/HandleInvalidRepoName.ts [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+    );
+
+    if (!isValidRepository) {
+        const warningBuilder = await modify
+            .getCreator()
+            .startMessage()
+            .setRoom(room)
+            .setText(
+                `Hey ${sender.username}! Provided repository doesn't exist or you need to login to access private repo.`
+            );
```
Comment (samad-yar-khan) [inline github/handlers/HandleInvalidRepoName.ts:43]: @Nabhag8848 I think this text should be `Hey ${sender.username}! Provided repository doesn't exist` if the access token does exist. If the access token does not exist the text can be `Hey ${sender.username}! Provided repository doesn't exist or you need to login to access private repo.`.  Conditionally rendering something like this, will be low effort but lead to a better user experience.

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]
@Nabhag8848 , minor changes. Please take a look and we will merge this 💯 thanks for the contributions 🥇

**Comment by Nabhag8848** [comment]
Hey, @samad-yar-khan made the appropriate changes. Thanks!

**Review by samad-yar-khan — APPROVED** [review]
LGTM @Nabhag8848 . Thanks for your contribution 💯
