### PR TITLE
[FIX] Description Under Overview Action Showing null

### LINKED ISSUE #38: [BUG] Description Under Overview Action Showing `null` when Repo has No Description
### Description:
- By executing  `/github Username/RepositoryName` for the **Repository having No description** and then interacting with `overview` ActionButton we get Overview of the provided repo. Now there might be the case that description of the repo is not provided by the owner in such cases description field from Github API returns `null` and thus description field in RocketChat renders as `null` value in text.

- Now, Instead of rendering `null`, we can provide the description field as `No description provided.`
### Steps to reproduce:

1. Run command `/github Username/RepositoryName` for the repository having no description.
2. Tap Overview Button
3. Look at the description field showing `null`

### Expected behavior:
- If the description is not there in repository meaning is equal to type `null`, provide the text: `No description provided`
Expected Description field

### Actual behavior:
- The description field as you can see are `null` and there are **redundant `backticks`** in the text which also needs to be removed. 
 Description Field Null
Null Field

### Additional context

- Redundant Backticks as mentioned and you can see in above Screenshot also needs to be removed.

### Note: 
- [x] Willing to work on the issue.

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Issue(s) 

Closes #38 

##  Fixed Bugs
- [x] Removed redundant backticks around the description and tags under Overview of Repository
- [x] `No description provided` text instead of `null` when the repository doesn't have a description.

Screenshot from 2022-12-04 16-13-04

### CODE REVIEW

File: github/lib/repoDataMessage.ts [hunk 1]
```diff
@@ -64,6 +64,12 @@ export async function repoDataMessage({
         });
     }
 
+    let description: string | null = resData.description;
+
+    if(description === null){
+        description = 'No description provided.';
+    }
+
```
Comment (samad-yar-khan) [inline github/lib/repoDataMessage.ts:72]: Hey @Nabhag8848 , thanks for solving this for us. Works well  :rocket:works !

But maybe we can do something like this 
` const description = resData.description || 'No description provided.';` 

This will make sure that the description is const and is not updated before sending it to the main channel. Also it fits with the code style we have in this file and saves some lines.

Comment (samad-yar-khan) [reply github/lib/repoDataMessage.ts:72]: @Nabhag8848  Can this PR be extended to fix some other places where we are showing null values ?

**Review by samad-yar-khan — COMMENTED** [review]
@Nabhag8848  Thanks for your PR :rocket: Added some suggestions, can you please take a look ?

File: github/lib/repoDataMessage.ts (hunk 1 above)
Comment (Nabhag8848) [reply github/lib/repoDataMessage.ts:72]: Yep! we can do that. Do you encounter any nulls, possibly i didn't encounter yet? if you have point me up.

Comment (Nabhag8848) [reply github/lib/repoDataMessage.ts]: Hey, @samad-yar-khan . I found lot of places where there is asyncronous operation without `await` and vice versa. should i make the commits within this PR? also we can merge my PR #41 branch with this one to make it bigger or we will include issue #47  within PR #41 later. 
How should we proceed.

**Comment by samad-yar-khan** [comment]
@Nabhag8848  Can you please remove the last commit and make a separate Issue / PR  to explain the position if `await` in calls since that does not fit the purpose of this PR?

File: github/GithubApp.ts [hunk 2]
```diff
@@ -162,7 +162,7 @@ export class GithubApp extends App {
             configuration.slashCommands.provideSlashCommand(ghCommand),
             this.getOauth2ClientInstance().setup(configuration),
         ]);
-        configuration.scheduler.registerProcessors([
+        await configuration.scheduler.registerProcessors([
```
Comment (samad-yar-khan) [inline github/GithubApp.ts:165]: @Nabhag8848  Can you please put these `await` changes in a separate PR ?  It does not fit the purpose of this PR.

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]

File: github/GithubApp.ts (hunk 2 above)
Comment (Nabhag8848) [reply github/GithubApp.ts]: Yep! thanks.

**Comment by Nabhag8848** [comment]
> @Nabhag8848 Can you please remove the last commit and make a separate Issue / PR to explain the position if `await` in calls since that does not fit the purpose of this PR?

Thanks @samad-yar-khan and thanks for pointing out. done removing the same and learn the lesson, i should not commit changes without acknowledgement.

**Comment by samad-yar-khan** [comment]
@Nabhag8848 LGTM ! you can add the `async-await` changes in a different PR . Thanks for the PR !
